version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    day: "monday"
    time: "04:00"
    timezone: Europe/Berlin
  labels:
    - "npm dependencies"
  open-pull-requests-limit: 5
