export { ariety } from './variadic/ariety'
export { existy } from './existy'
export { identity } from './identity'
export { isArray } from './is-array'
export { isBoolean } from './is-boolean'
export { isNaN } from './is-nan'
export { isNull } from './is-null'
export { isUndefined } from './is-undefined'
export { truthy } from './truthy'
export { type } from './type'

export { unary } from './variadic/unary'

export { doWhen } from './do-when'
export { executeIfHasField } from './execute-if-has-field'
